### ISSUE TITLE
Just noticed your issue post on my github

### ISSUE THREAD

**Issue by rduart** [carl1961/Arduino-Uno-Tesla-Coil-Winder#1]
This is great work.   I will be following to see how you are progressing.

**Comment by rduart** [comment]
Please let me know if you ever want to do a WebEx, teams or some other online meeting.   I would be happy to jump on a session to see what we can learn from each other.

**Comment by carl1961** [comment]
Thanks @rduart , I would most likely be me doing the learning. I'm currently testing to use a stepper motor for a tension, you can apply like between .3 to max 2 volts across any winding and it will give a slight resistance. that like 2 volts is most likely to much.

**Comment by rduart** [comment]
Carl1961, do you happen to know how many starts your lead screw has?   My lead screw has 4 starts.   I had an issue testing a longer coil with 34 AWG wire.  The wire carriage that moves the wire forward started falling behind.   It got so far behind that it finally skipped backward.   Just wondering what you have.   I am recalculating all the steps for the wire sizes.   I know you just changed yours wire carriage steps.   Any suggestions?

**Comment by rduart** [comment]
Carl1961, I think I might have found a solution to the my last post.   I adjusted the awgStep again, but more testing is needed.   Also, just to let you know I found 1 additional problem.   The coil that my machine is building is greater than the MM specified.  For example:   100MM coil, 34 AWG wire, 624 turns.   Should create a coil 100MM long instead it is creating a coil 114MM.   The spacing is looking good, so not totally sure what to do about this issue.   My calculations are with 1 or 2 turns difference from JavaTC.    More thinking and updates todo.    Please let me know how your stepper motor tension is working.    A conversation might be good at some point. 
![20240527_072621](https://github.com/carl1961/Arduino-Uno-Tesla-Coil-Winder/assets/10364651/595037ff-e129-4f27-9051-df5670b2d7c3)

**Comment by carl1961** [comment]
My lead screw is one start 2mm pitch 2mm per resolution
My stepper is 16 micro steps, 3200 steps per revolution, 1600 steps for 1mm
so if you have a 4 start that's most likely 8mm per resolution, if your 16 micro steps, that would be 400 steps for 1 mm move. (3200 /8)
 I figured my steps this way

//awgStep = 50; 1/.40386= 2.47610  1600/2.47610 = 646.17745 LEAD SCREW 2MM PITCH @ 16 MICROSTEP = 1600 STEPS PER MM
  awgStep = 646;
  wiredia=.40386;  // Wire Diameter

1mm divided by wire dia. ( save that number 2.4761 ) 
then divide your steps per 1mm (400 divided by 2.4761  161.544 steps to move .40386 (all this depends on your micro steps  settings on your driver)

**Comment by carl1961** [comment]
So far tensioner with stepper seems working ,as you turn the Potentiometer, the stepper gets tighter. I posted a video on Rumble.com with coil winding and unwinding. just the drag from the stepper was ok for this thread test. I still got to draw a schematic up. I used a cheap DC controller across one stepper coil winding. used a 2 channel 12 volt relay, wires on Normal Open, first I switch relay with 12v from dc motor controller, then found I needed to switch it when Arduino uno was on (could use 5v relay now, because Arduino io pins). I had to disconnect the 2 stepper wires going to stepper driver on  the Arduino, because it did weird things (like resetting) from the voltage back feeding through stepper driver.

https://rumble.com/v4y38a9-tesla-coil-winding-and-unwinding-machine.html

**Comment by carl1961** [comment]
I put the fishing string back on machine, I see a slight lag with my lead screw, but I think it is the tolerance on the fishing string off. it said .4mm so I used 26awg. also this 3D printed spool looks to need to be sanded smooth, the layer grooves seem to effect the coil wrapping tight.

![WIN_20240530_08_10_19_Pro](https://github.com/carl1961/Arduino-Uno-Tesla-Coil-Winder/assets/3056821/2530246d-799e-4f16-a6a7-b6bf742abf26)

spool groves

![WIN_20240530_08_20_35_Pro](https://github.com/carl1961/Arduino-Uno-Tesla-Coil-Winder/assets/3056821/6a0faf38-d309-4b00-949f-ac1fff8b2a53)

 Measuring Laser Start to finish, 100mm was 104.85

![WIN_20240530_08_33_20_Pro](https://github.com/carl1961/Arduino-Uno-Tesla-Coil-Winder/assets/3056821/8262d13c-638e-4e0b-9e85-8d3268dd64db)

That looks to be the amount of coil over shoot.

![WIN_20240530_08_35_37_Pro](https://github.com/carl1961/Arduino-Uno-Tesla-Coil-Winder/assets/3056821/c8d482fa-4704-4174-b891-b816ec94f28b)

I take the fishing line off tolerance and spool not smooth to be my issues.

By the way, Your coil above looks Awesome.

**Comment by rduart** [comment]
This is great work and great insight.   I liked your video.   Thanks, the insight on the lead screw.  Please keep me updated on the tensioner.  It would be great to have more control of the wire tension.  I noticed that with larger wire the wheels I am using are keep the wire more or less tight.   With the smaller sized wires, I have noticed some slack in the wire as if toggles between the coil turns and the wire carriage moving.   I will push a new version of the code in the next few days.  I have worked through awg 32, 34, and 36 sizes.   I am considering building an alternative version of the code that allows the user to enter the number of turns they want or the length of the coil.   I am thinking someone might want a 1000 turns exactly on the coil.    I will keep you updated.

**Comment by rduart** [comment]
On the coil being smooth.  I have noticed issues when I am using PVC from the big box store.   It needs to be sanded to remove any scratches or scuffs that may be on the surface.    I had some acrylic tube that I have been testing with.   It is perfectly smooth and is working well for testing.

**Comment by carl1961** [comment]
been studying wire, enamel coating is like .0285 mm, adds up over 100mm coil to like 7mm

https://www.digikey.com/en/resources/conversion-calculators/conversion-calculator-wire-size


AWG    mm    Enamel   Enamel thickness
18   1.0237
19   .9116


*26   .4049
*28   .3211   .35         .0289
*30   .2546
*32   .2019   .23         .0281
*34   .1601
*36   .1270
 38   .1007

                  average .0285
				  
Coil length		26 AWG	  
100mm coil  / .4049 	
Turns 	246.9	

Turns                enamel thickness 	   MM
246.9				  .0285                7.03


100mm coil  / 	(.4049 + .0285) 
100mm coil  /      .4334

Turns      230.7 vs 246.9 

Enamel thickness really added up.

**Comment by carl1961** [comment]
Made these adjustments for sizes from above post, adding the .0285 to each for the enamel coating.
//awgStep = 50; 1/.4325= 2.31213  1600/2.31213 = 692.00261 LEAD SCREW 2MM PITCH @ 16 MICROSTEP = 1600 STEPS PER MM

*26   .4325
*28   .3496    
*30   .2831
*32   .2304    
*34   .1886
*36   .1555

100MM is right on, will sand that spool next.

![WIN_20240530_22_41_43_Pro](https://github.com/carl1961/Arduino-Uno-Tesla-Coil-Winder/assets/3056821/b10885bb-e837-4397-b07d-09b33c237e54)

Sanding the spool did the trick for tighter coil. No lag with the lead screw.

![WIN_20240530_23_41_41_Pro](https://github.com/carl1961/Arduino-Uno-Tesla-Coil-Winder/assets/3056821/7fd7c4d9-67b6-4ec8-8bbc-9f3db7f5a633)
![WIN_20240530_23_54_39_Pro](https://github.com/carl1961/Arduino-Uno-Tesla-Coil-Winder/assets/3056821/40d29b68-3c7c-45e5-b8c6-a6f838d61b32)

Think I am ready for the real wire.

**Comment by carl1961** [comment]
Much better tighter coil, but trying to smooth the 3D-Printed spool, with a toy lathe actually chipped the plastic and effecting the coil winding. Time to find some PVC pipe.

![WIN_20240531_06_56_39_Pro](https://github.com/carl1961/Arduino-Uno-Tesla-Coil-Winder/assets/3056821/6a20b92a-4e28-41d8-a89c-b67ea27d23ff)

**Comment by carl1961** [comment]
Found a piece of 1 1/4 PVC, what a difference. I see no gaps or laps.

![first coil](https://github.com/carl1961/Arduino-Uno-Tesla-Coil-Winder/assets/3056821/175a26df-6703-41ca-b8fd-c4361bf5daa3)

**Comment by rduart** [comment]
Wow that looks perfect, so good.   Your numbers are very close to what I was seeing when playing with the measurements.   I had not worked on awg26 yet.   I will plug-in your numbers and see what happens.   PVC pipe makes a big difference.  If you have cuts, or scuffs you will need to sand has been my experience.   Acrylic makes really smooth coils, but it's expensive.  Yours winding is looking so good.      By the way are you building Telsa coils?   What's your reason for building the winder?

**Comment by carl1961** [comment]
yes built a board from  https://www.instructables.com/Making-the-Ultimate-Class-E-Musical-Tesla-Coil-Sin/  

I want to accomplish one tesla coil activating another tesla coil to produce wireless power, say lighting leds on a miniature house to prove tesla's dream. them maybe donate to a local school for science. so trying low power so it is safer.

**Comment by carl1961** [comment]
varnishing


https://github.com/carl1961/Arduino-Uno-Tesla-Coil-Winder/assets/3056821/7fd964a8-ad7e-4d0f-961d-6473c2da59d8

**Comment by rduart** [comment]
It's so funny my sons are on the same path as you.  One of sons got the idea to build a Tesla coil.  He built a small one designed by Jay from the Plasma channel.   Next, he built several more based on other YouTuber designs.   The last two he built were based on Zack Labcoatz SSTC and QCW (Staccato DRSSTC) telsa coil.   He is planning on building the same one you are ( Lab Coatz Class-E Musical Tesla Coil).   We got tired of winding Awg34 gauge wire by hand or with the help of a servo motor and foot peddle.   I enlisted my other son to help me develop a winder seeing more tesla coils in the future.   The engineering is a great learning experience for both of them.   

Here is a couple that he made.  
![20240415_105021a](https://github.com/carl1961/Arduino-Uno-Tesla-Coil-Winder/assets/10364651/39481db4-60e0-4b8c-8fa7-35221c3356cc)


Your work is looking so go.   I really like your idea of 3D printing the parts.   Any school that has a 3D printing lab will be able to cost effectively reproduce your design.    I have been encouraging the boys to take a look at your GitHub.  They could use many of your design ideas in our winder.

I created a AWG26 coil.   100MM long using your numbers.    It came out perfect 100MM, nice and tight.   I will update values and pushup a new version.  Also still planning on adding an option to create a coil with x number of turns for the guys that wants 1000 turns.

![Awg26Wire](https://github.com/carl1961/Arduino-Uno-Tesla-Coil-Winder/assets/10364651/c2c79a0f-3020-4f15-ae10-4416100aa4ef)

**Comment by carl1961** [comment]
I did have to add like 12 extra steps to that AWG number for what ever reason, maybe tolerance of the wires, the lead screw was slightly lag and me being so close to the coil it does not take much back drag before double wraps happen. During the first run with the PVC pipe, about half way done, I pressed pause (when the coil motor stopped) and advanced the head slightly. 

I have extra boards left  and some extra special parts, I can send you a couple and what parts they may need (Free). when I ordered I got 10 of each.
UCC27524P chip
74HC14P
APT37F50B
100V 1500pF 
GBU1510 Bridge Rectifier
555 timer
TVS Diodes 400v and 18v
IN5404 Diode
2WATT 4.7ohm resistor
email me if I can help your Boy's with the stuff save them some money, be my honor.   cmshelton2021@protonmail.com
Extra Parts

![WIN_20240601_21_24_28_Pro](https://github.com/carl1961/Arduino-Uno-Tesla-Coil-Winder/assets/3056821/da7a7b80-8ab9-418f-96df-1ab32cd57792)



I did a my version of that guys 3d parts too

![WIN_20240601_21_25_39_Pro](https://github.com/carl1961/Arduino-Uno-Tesla-Coil-Winder/assets/3056821/b353b04e-b46a-4cc3-b6a6-f9f211175982)

**Comment by carl1961** [comment]
My STL Files with ones to fit 1-1/4 PVC pipe
[ELECTRA_Tesla_Coil.zip](https://github.com/user-attachments/files/15523966/ELECTRA_Tesla_Coil.zip)

**Comment by rduart** [comment]
Please me know when you have it working.   I would very much like to see it working.   Thank you so of the offer.  I will talk with the boys and email you or have one of them email you.    Do you have an oscilloscope?     I currently do not.   I think Labcoatz said you need one for tunning?

**Comment by rduart** [comment]
My sons would love to take you up on your offer.   I will email you my contact information.    Thank you so much.

**Comment by carl1961** [comment]
I have a Fnirsi -1C15 and a couple  DSO138 (in video)  I'll send you one. I will show my progress, Labcoatz did not really show much how he did that, so I will most   have to research testing for the frequency.

https://www.youtube.com/watch?v=ijZJ_7elZqE
